version: "3"

services:
  web:
    build: ./web
    ports:
      - 5000:5000
    volumes:
      - ./web:/web
    environment:
      PORT: 5000
      ESLINT_NO_DEV_ERRORS: "true"
  api:
    build:
      context: ./api
    entrypoint: /api/docker-entrypoint.sh
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./api:/api
      # - bundle_cache:/bundle_cache
    cpu_quota: 50000
    cpuset: "1"
  db:
    image: postgres:12.5
    # allow host machine to connect to db using port 5433
    # w/o colliding to existing postgres installed
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: app_dev,app_test
      # POSTGRES_DB: app_dev
      POSTGRES_PASSWORD: postgres

volumes:
  # bundle_cache:
  dbdata:
